export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const ADD_CURR_LOCATION = "ADD_CURR_LOCATION";
export const START_RECORDING = "START_RECORDING";
export const ADD_LOCATION = "ADD_LOCATION";
export const STOP_RECORDING = "STOP_RECORDING";
